Repository HoangMinhKhoiPham/COMP-353, pull requests merged in 2023-04, with the labels that each got.

#31 #2 #4 #6 Dbug
  database.php
  ii.sql
  main/Facility/deleteFacilities.php
  main/Facility/displayFacilities.php
  main/Facility/editFacilities.php
  main/Facility/insertFacilities.php
  main/Infection/deleteInfection.php
  main/Queries/querySeven.php
  main/Schedule/editSchedule.php
  vi.sql
Labels: bug

#34 Add weekly notification
  pureSQL/pureSQL/EmailDetail.sql
  pureSQL/pureSQL/generateEmail.sql
  pureSQL/pureSQL/getScheduleForTargetDay.sql
  pureSQL/pureSQL/sendEmails.sql
  pureSQL/pureSQL/weekly_notification.sql
Labels: enhancement, Query 20

#33 #4 #6 Debug Schedule and Vaccination scripts
  main/Facility/insertFacilities.php
  main/Schedule/deleteSchedule.php
  main/Schedule/editSchedule.php
  main/Schedule/insertSchedule.php
  main/Vaccination/deleteVaccination.php
  main/Vaccination/editVaccination.php
  main/Vaccination/insertVaccination.php
  pureSQL/trigger/TriggerCancelSchedule.sql
  pureSQL/trigger/TriggerTimeOverlap.sql
  pureSQL/trigger/TriggerUpdateManager.sql
Labels: bug, Query 3, Query 5

#39 Update trigger_cancel_schedule
  pureSQL/trigger/TriggerCancelSchedule.sql
Labels: bug, enhancement
